### ISSUE TITLE
How to setup on MacM1 with iphone

### ISSUE THREAD

**Issue by rohitsangwan01** [Cemu0/ESP32Test#1]
Hey , am trying to setup this , but this PlatformIO and all is new to me , trying to gather info but its not working out , if possible can you create a step wise documentation or video to run this

**Comment by Cemu0** [comment]
Hi

**Comment by Cemu0** [comment]
Hi there, thank you for your attention, I do have the plan to make a video for this repo but currently cannot gather time for this. 
Unfortunately, I don't have a Mac M1 so here is some advice:
1. For Using PlatformIO, you should download VSCode and open the repo with VSC, things should be automatically installed, and you can upload the code to ESP32 using the button. (I should compile to a hex file for easier upload instead of  leaving so) 
2. To run the host app (the capture mouse and keyboard software) setup on Mac could have tricky with permission, but you should still be able to do so.

**Comment by rohitsangwan01** [comment]
@Cemu0 Thankyou for reply , i tried but setting up ESP32 and all is new to me , i was getting lots of error ( followed some docs from internet ), am native app developer so no idea regarding this , but issue with MacM1 is 
we cannot pair later IOS devices with latest MacOs  , they just disconnect automatically , which breaked all the existing solutions to control iphone with mac ( like Vysor )

**Comment by Cemu0** [comment]
Can you give me the detailed error? when setup PlatformIO?. I am not sure what you mean with pair later IOS with the latest macOS, My system works like this: Capture keyboard and mouse from your keyboard --- send to ESP32 over serial ----> ESP32 --- send key and mouse over BLE ----> your device.

**Comment by rohitsangwan01** [comment]
@Cemu0 oh ok , i guess i understand this concept wrong , i thaught this program turns operatingSystem into a bluetooth HID device for our mobile , and works like this : 
capture keyboard and mouse -> send to mobile , 
We can do this using bluetooth HID android , so i thaught its something similar for Desktop
so i guess you can  close this issue

**Comment by Cemu0** [comment]
Oh, I see, that you want to reuse the PC Bluetooth to control your device. As I know for Linux there is a library for that but not on macOS. That's all for now.
